*** Settings ***

Documentation  This is a resource file, that contains variables for Swaglabs app
...            on my iphone for checkout complete page


*** Variables ***

${TEXT_ORDER_CONFIRMATION}  THANK YOU FOR YOU ORDER Your order has been dispatched, and will arrive just as fast as the pony can get there! BACK HOME

${BACK_HOME_BUTTON}       test-BACK HOME

${WRONG_TEXT_FOR_ORDER}   Sorry your ordet can´t be delivered beacue we have technical error 
